version: "3.9"

services:
  # -------- Postgres --------
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # -------- Auth API --------
  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    container_name: auth_api
    depends_on:
      - postgres
      - data-api
    env_file:
      - ./auth-api/.env
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  # -------- Data API --------
  data-api:
    build:
      context: ./data-api
      dockerfile: Dockerfile
    container_name: data_api
    depends_on:
      - postgres
    env_file:
      - ./data-api/.env
    ports:
      - "8082:8080"

volumes:
  postgres_data: